### ISSUE TITLE
What should I do when I have multiple subscriptions?

### ISSUE THREAD

**Issue by insoxin** [xditya/YouTubeFeeds#1]

**Comment by xditya** [comment]
There's nothing that can be done, right now. Maybe I'll add support for multiple subscriptions in future.

**Comment by insoxin** [comment]
> There's nothing that can be done, right now. Maybe I'll add support for multiple subscriptions in future.

Waiting

**Comment by abelby14** [comment]
Where I find redis URL?

**Comment by amitkr-codes** [comment]
@abelby14 redislabs.com

**Comment by abelby14** [comment]
But inside my redis database where is the url? The url is the public endpoint? For the bot to start working, I only have to fill in the variables and hit the deploy button, or do I have to do something else? (I have already created the database and everything)

**Comment by amitkr-codes** [comment]
@abelby14 Endpoint is url, scroll down you will get password

**Comment by abelby14** [comment]
I'm sorry for bothering. 1. I have created the bot in telegram*, 2. I have created the database in redis. 3. I have created an app in heroku with the configuration variables and I have clicked on the "deploy app" button.

After doing these steps, should the bot work? Or do I need to do something else? Thanks.

**Comment by xditya** [comment]
> I'm sorry for bothering. 1. I have created the bot in instragram, 2. I have created the database in redis. 3. I have created an app in heroku with the configuration variables and I have clicked on the "deploy app" button.
> 
> After doing these steps, should the bot work? Or do I need to do something else? Thanks.

Bot on instagram?

Send logs, if the bot isn't working.

**Comment by abelby14** [comment]
![image](https://user-images.githubusercontent.com/63512230/143776408-602f5d60-d454-4d47-a6b0-0b2c715848a7.png)

This appeared to me after making the deployment, but the bot does not inform me of the videos that the channel that I put up uploads.

**Comment by xditya** [comment]
> ![image](https://user-images.githubusercontent.com/63512230/143776408-602f5d60-d454-4d47-a6b0-0b2c715848a7.png)

Are you sure you used the link provided in the repository readme?

**Comment by abelby14** [comment]
Yes, this link: https://heroku.com/deploy?template=https://github.com/xditya/YouTubeFeeds

**Comment by xditya** [comment]
> Yes, this link: https://heroku.com/deploy?template=https://github.com/xditya/YouTubeFeeds

![IMG_20211128_215118](https://user-images.githubusercontent.com/58950863/143776703-6bedf536-36a2-4bbd-bf18-0477dfe4229a.jpg)

Turn on the worker dyno

**Comment by abelby14** [comment]
Ohh now its working. Thanks!!!!! And how would I make changes to the code and make it work?

**Comment by xditya** [comment]
> Ohh now its working. Thanks!!!!! And how would I make changes to the code and make it work?

It's working, right, what more to change?

**Comment by abelby14** [comment]
Now shows this.

![image](https://user-images.githubusercontent.com/63512230/143776878-13f918a5-8e2d-4928-801d-603ceafbfcbd.png)

Later, I would like that instead of sending 1 message to the group spam 10-20 messages

**Comment by xditya** [comment]
> Now shows this.
> 
> ![image](https://user-images.githubusercontent.com/63512230/143776878-13f918a5-8e2d-4928-801d-603ceafbfcbd.png)
> 
> Later, I would like that instead of sending 1 message to the group spam 10-20 messages

That's upto you to fork, edit and redeploy.

**Comment by abelby14** [comment]
Are these errors in the application log normal?

**Comment by xditya** [comment]
> Are these errors in the application log normal?

Yes. It happens when you haven't added the bot/started it from the ids in owners. Do it first.

**Comment by abelby14** [comment]
I dont understand, Where do I start the bot? The bot is already joined to the group

**Comment by xditya** [comment]
> I dont understand, Where do I start the bot? The bot is already joined to the group

The `CHATS` variable has a user with id 67042... ?
If yes, /start the bot from that user account.

**Comment by abelby14** [comment]
No, 607428809 is the chat id

**Comment by xditya** [comment]
@abelby14 Add a -100 to the start of the id (if it's a supergroup

**Comment by abelby14** [comment]
If in CHATS I put my telegram user id, the bot send mssj to my private, but if i put group id the bot dont work

**Comment by xditya** [comment]
@abelby14 Added -100 in start of the chat id?

**Comment by abelby14** [comment]
![image](https://user-images.githubusercontent.com/63512230/143778209-cd17ec81-4c76-427c-8ce0-d47d3d7af940.png)

![image](https://user-images.githubusercontent.com/63512230/143778241-9f116efe-f667-402d-9ebd-6d70c6719261.png)

**Comment by xditya** [comment]
> ![image](https://user-images.githubusercontent.com/63512230/143778209-cd17ec81-4c76-427c-8ce0-d47d3d7af940.png)
> 
> ![image](https://user-images.githubusercontent.com/63512230/143778241-9f116efe-f667-402d-9ebd-6d70c6719261.png)

Contact me on [@BotzHub](https://t.me/BotzHubChat)

**Comment by xditya** [comment]
The repository now supports multiple subscriptions and multiple chats!

https://t.me/BotzHub/251
